services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.2.2
    container_name: clickhouse
    environment:
      CLICKHOUSE_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}   
      CLICKHOUSE_USER: ${OPENLIT_DB_USER:-default}                   
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ports:
      - "9000:9000" 
      - "8123:8123" 
  
  openlit:
    image: ghcr.io/openlit/openlit:latest
    container_name: openlit
    environment:
      INIT_DB_HOST: clickhouse
      INIT_DB_PORT: 8123
      INIT_DB_DATABASE: ${OPENLIT_DB_NAME:-openlit}
      INIT_DB_USERNAME: ${OPENLIT_DB_USER:-default}
      INIT_DB_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}
      SQLITE_DATABASE_URL: file:/app/client/data/data.db
    ports:
      - "3000:3000"
    depends_on:
      - clickhouse
    volumes:
      - openlit-data:/app/client/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.94.0
    container_name: otel-collector
    environment:
      INIT_DB_HOST: clickhouse
      INIT_DB_PORT: 9000
      INIT_DB_DATABASE: ${OPENLIT_DB_NAME:-openlit}
      INIT_DB_USERNAME: ${OPENLIT_DB_USER:-default}
      INIT_DB_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}
    ports:
      - "4317:4317" 
      - "4318:4318" 
      - "8888:8888" 
      - "55679:55679" 
    depends_on:
      - clickhouse
    volumes:
      - ./assets/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml

  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: meilisearch
    ports:
      - "7700:7700" 
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=B-f5OebtKvWe-RsSYIZaTQQKys9bAtsoymGcWoXKJTM
    volumes:
      - meili_data:/meili_data # 将主机的 meili_data 目录挂载到容器中


volumes:
  clickhouse-data:
  openlit-data:
  meili_data: 