version: '3.9'

services:
  redis-master:
    image: 'redis:6.2.14'
    container_name: redis-masterslave-master
    ports:
      - "6379:6379"
    volumes:
      - ./master.conf:/usr/local/etc/redis/redis.conf
      - master_data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis-slave:
    image: 'redis:6.2.14'
    container_name: redis-masterslave-slave
    ports:
      - "6380:6379"
    volumes:
      - ./slave.conf:/usr/local/etc/redis/redis.conf
      - slave_data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--slaveof", "redis-masterslave-slave", "6379"]

volumes:
  master_data:
  slave_data: