version: '3.9'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # MinIO Web 界面和 API 的端口
      - "9001:9001"   # MinIO 控制台的端口（如果启用）
    volumes:
      - minio_data:/data  # 数据存储卷
    environment:
      MINIO_ACCESS_KEY: "minioadmin"  
      MINIO_SECRET_KEY: "minioadmin"  # 替换为你自己的秘密密钥
    command: ["server", "/data", "--console-address", ":9001"]  # 启动 MinIO 服务器并启用控制台

volumes:
  minio_data:
