version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512M"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    image: logstash:7.16.2
    container_name: logstash
    volumes:
      - /Users/huangqiang/code/idea/company/authing/authing-security-platform/audit_log:/logstash/input
      - ./approval-pipeline.conf:/usr/share/logstash/pipeline/approval.conf
      - ./logstash-pipelines.yaml:/usr/share/logstash/config/pipelines.yml
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  es_data: 